application: vaporista-eu
version: 10
runtime: python27
api_version: 1
threadsafe: true

builtins:
 - appstats: on

libraries:
- name: PIL
  version: latest
- name: webob
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest
- name: lxml
  version: latest
- name: numpy
  version: latest
- name: webapp2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: client/favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: client/robots.txt
  upload: static/robots\.txt

- url: /client/font/(.*\.ttf)
  mime_type: application/octet-stream
  static_files: client/font
  upload: static/font/(.*\.ttf)

- url: /client
  static_dir: client
  expiration: "7d"

- url: .*
  script: server.main.app